### ISSUE TITLE
Emulator simulation is User Terminals version 2 or User Terminals version 3 ?

### ISSUE THREAD

**Issue by carrie17** [quarkslab/starlink-tools#1]
Hello，Could you tell me which version the emulator simulated，thank you !

**Comment by CarloRamponi** [comment]
The provided Device Tree is the one of version 2 (`rev2_proto3`), as you can see [here](https://github.com/quarkslab/starlink-tools/blob/816b64c29a8a32a1f3d0d2310c332c04d50824dd/emulator/FDTs/custom.dts#L21)
