### ISSUE TITLE
The Golang Ghidra version

### ISSUE THREAD

**Issue by geonno** [quarkslab/starlink-tools#4]
Which version of Ghidra did you use? Some versions of Ghidra says that the version is not compatible with golang plugin you've mentioned in the quark's lab blog. thanks

**Comment by CarloRamponi** [comment]
At [this url](https://github.com/mooncat-greenpy/Ghidra_GolangAnalyzerExtension/releases) you can find for each version of the plugin, the list of supported Ghidra versions.
If yours is not present, you have to rebuild the plugin for that version.

Please do not open issues unless there is a problem in one of the tools of this repo.

**Comment by geonno** [comment]
Thank you :) I'll keep that in mind
